### ISSUE TITLE
Code refactoring based on TA feedback

### ISSUE THREAD

**Issue by neoJINXD** [neoJINXD/Eternity#17]
![image](https://user-images.githubusercontent.com/12958600/85182907-0e007a80-b258-11ea-8de4-bb45ab71410e.png)

**Comment by EmanuelUnity3D** [comment]
I'm not sure what exactly is meant here. I recognize that there are different ways of organizing the functions but I think that our chosen pattern is pretty clear? 

The only thing I can think of that might be confusing is what does and does not belong in common. For example, the quote above suggests that generate_e() should be in common, however, I disagree. generate_e is a helper to exp and exp alone so it should go in exponents and logarithms as per the philosophy of modularization.

Anyways, I removed the exponents_and_logs and logs helper file and added to the common file to try and make the distinction more clear. We might be able to do more but I leave it to you guys for now to come back with more input. Maybe we could add comments to the head of each file to explain the file's purpose? It might be a bit redundant since the names of the files are pretty descriptive but it's worth considering.

**Comment by SwatiPareek** [comment]
I agree with your overall sentiment about the file names being pretty self-explanatory. 

The areas which probably were somewhat confusing were the exponents separate helper function. 
We also use the same function to calculate e and to calculate e^x which I initially thought was the more concise way of going about it. The issue with this from a readability perspective is that the dual functionality isn't as obvious from the name itself.  Thus we either change the name or create a separate function for generating the constant e, as we have for pi. 

Another thing  the TA pointed out is that we have exponents had a helper function class exclusive to it.
Having a little write-up above the file may help clarify this.
