### ISSUE TITLE
Iteration II of Calculator UI

### ISSUE THREAD

**Issue by EmanuelUnity3D** [neoJINXD/Eternity#22]
There are a couple of things to consider regarding the UI for iteration II.

The priority should be adding a button on the calculator for each of the functions requested by the professor. I made some changes to the back-end so that we can use all of them by manually entering their names, however, some of the function names might not be obvious to the user.

Another nice thing to have would be to allow the user to submit input by pressing enter instead of having to click on the "calculate" button. This would have the added benefit of making testing easier. I briefly tried to get this working myself but couldn't get the event listener for the enter key to work.

Lastly, it might be worth thinking about how to clean up the interface. This could include improving the alignment of UI elements, reworking the colors, fonts, and/or shapes, and/or reworking the layout. This is pretty low on our priority list though since a working calculator is more important than a pretty one.

**Comment by SwatiPareek** [comment]
Appreciate the thought into what needs to be done, however I think these should be split into multiple issues.
If we intend on using this feature to increase our productivity, we want to make the summary and description of each issue as concise and modular as  possible, otherwise it will not help up divide tasks very efficiently. 

The description should be clear enough to allow someone else to take on that task if need be (i.e. which branch are your changes to the back end in that would allow us to manually enter names? which functions will not be obvious to the user? why have we not chosen to go with standard function names like sin or e^x that are found on the calculator).

**Comment by EmanuelUnity3D** [comment]
Fair point. I tried removing this issue so that I can break it down into a couple of new ones but I don't think I have the permission to delete issues. I can only close them.

As for the naming, names like e^x are impossible because typing e^x into the calculator would generate e^1 and call Pow(e^1, x) with it. I had to come up with some actual function names to get around this issue. I did try to base the names off of existing math libraries though so that I wasn't getting them from nowhere though.
