### ISSUE TITLE
Fix precision issues

### ISSUE THREAD

**Issue by cpotteck** [neoJINXD/Eternity#32]

**Comment by SwatiPareek** [comment]
One proposed solution to this was using the Decimal class (https://docs.python.org/3/library/decimal.html) instead of floats to overcome their limitations in precision 

This issue may involve truncating the output and is thus perhaps closely intertwined with the following issue: Output formatting and truncation #34

**Comment by SwatiPareek** [comment]
In order to do this we should tackle fixing pi. 
For nor, pi is only precise to 5 decimal places. This is problematic because pi is used to calculate other functions/constants
I briefly tried using the Decimal class to fix this but it did not improve the precision (could just be some oversight on my part)
