### ISSUE TITLE
Tacit multiplication isn't allow

### ISSUE THREAD

**Issue by VisusAdAstra** [neoJINXD/Eternity#40]
5(5+3) correct but (5+3)5 give error

**Comment by EmanuelUnity3D** [comment]
I think we already addressed this during our meeting. Technically, all multiplication should be done with the * operator. 5(5+3) happens to work because a * is inserted by the parser to the left of bracketed factors. That being said, it isn't the proper way of inputting a multiplication (for our calculator).

We could look into making (5+3)5 work as well but we should relabel it as a feature and add fill out the issue documentation. That being said, I don't think that it's a very high priority task at the moment.

**Comment by tarads443** [comment]
Decided to put this in the user guide
